elifesciences/elife-bot-formula

salt/elife-bot/init.sls

Builder copies files in /tmp to (e.g. `/tmp/highstate.sh`) to execute
them on a target EC2 instance.
However, when a Salt state mounts something over /tmp the process fails
at the end when trying to remove `/tmp/highstate.sh`, as the original
/tmp folder has been shadowed by the new mount.
Therefore, in the arm wrestling between bot and builder, builder gets to
use /tmp.
This change does not affect any production instance, as I would like to
get it in before (re)creating `elife-bot--prod` and porting to it.

Changing temporary directory to /bot-tmp

---

salt/elife-bot/init.sls

This should not interfere with running workflows as it only acts on files older than 2 days.
When instances are turned on, they stay up for at least an hour, so this should suffice to clean up their /bot-tmp folder before they are shutdown again. Only executing it at 2 AM sometimes lead to the cleanup not being executed for several days until the disk fills up.

Running cleanup cron every hour

---

salt/elife-bot/init.sls

This is a case similar to bot-lax-adaptor: a sidecar application that sometimes need to be switched to a particular commit/branch by an automated process.
To ease the switch to a new commit, we can use the `https` scheme rather than `ssh`. The latter would require to create an SSH key for the `elife-bot--*` EC2 instances.
/cc @gnott I don't expect this to impact anyone's work, but you never know

Use git+https for elife-poa-xml-generation

---

salt/example.top

turns out sejda, the replacement for pdfsam, requires java 1.8 and not the 1.7 installed.
a few reasons this passed tests:
* changes for strip-coverletter hadn't been merged in
* strip-coverletter had only been tested locally and within a new docker container
* no smoke test for strip-coverletter in elife-bot-formula
@giorgiosironi , @gnott , [I've reverted the merge in strip-coverletter](https://github.com/elifesciences/strip-coverletter/commit/e1ae5f3f096a662defed263bf6b258de3f422c6c) while the elife-bot machine has java8 installed and I add a smoke test to the elife-bot-formula to ensure it's happy
builder-private PR: https://github.com/elifesciences/builder-private/pull/93

switched to java8 for sejda

---

salt/elife-bot/strip-coverletter.sls

@giorgiosironi , what have you found to be the best way to handle permissions when bridging fs and container? 
in the strip-coverletter script the `--user` parameter is passed in with the id of the user currently running the script, but this will need to match the permissions of the `vol/` directory, which this PR sets to `root:elife` and `777`.
the test had been merrily running as the `root` user and had always been passing

makes the permissions on the writable docker dir more lenient

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

To include ``elocation_id`` in Crossref deposits for eLife articles, this config file will make it happen, only to be merged after this ``elife-bot`` PR though https://github.com/elifesciences/elife-bot/pull/694, because this config file is compatible with the latest release of ``elife-crossref-xml-generation``.

Bot, crossref.cfg file updated.

---

salt/elife-bot/config/opt-elife-poa-xml-generation-settings.py

Related to PR https://github.com/elifesciences/elife-poa-xml-generation/pull/331, this PR here should not be merged before the library PR is merged and deployed, otherwise the datasets file is not ready to be supported for overflow parsing.

In PoA library settings, add datasets to the overflow CSV file list.

---

salt/elife-bot/config/opt-elife-bot-pubmed.cfg

Adds support for the logic in the PR for the library https://github.com/elifesciences/elife-pubmed-xml-generation/pull/25  Will allow ``"Editorial note:"`` paragraphs in eLife articles to get a special label in the PubMed deposits. All other PubMed deposits will use the ``<AbstractText>`` tag when the updated library is deployed.

Add abstract_label_types property to the pubmed cfg file.

---

salt/elife-bot/init.sls

The SWF stuff failed in Vagrant due to lack of credentials.
I also have another problem with `strip-coverletter` failing to write to a volume because its user is `worker`, want to see if it reproduces.

Only execute SWF calls on AWS

---

salt/elife-bot/config/opt-elife-bot-digest.cfg
salt/elife-bot/init.sls

The ``digest.cfg`` file taken from the https://github.com/elifesciences/digest-parser library, making it available for the bot to load in activities.
It wasn't needed just yet except I moved the ``.docx`` output file naming logic into the library, and it is possible to specify the naming pattern in the ``.cfg`` file. Once the config file is available, I can change ``EmailDigest`` to be able to load the pattern from the config file (if available) rather than relying on the default naming pattern that is hard-coded in the library itself.
The contents of the config file will change in the future, especially when the footer content of the Medium post is specified here, although that may be some time in the future.

Add the digest.cfg config file.

---

salt/elife-bot/strip-coverletter.sls

this is to keep it inline with the uid of the Dockerfile

changes permissions on strip-coverletter's writeable 'vol' directory

---

salt/elife-bot/config/opt-elife-bot-digest.cfg
salt/pillar/elife-bot.sls

Cannot be merged before https://github.com/elifesciences/digest-parser/pull/62 is and the `digest-parser` library is updated in the `elife-bot` project.
I looked for an existing place to get `https://elifesciences.org` from the existing formula values, but in the end I added it as a new section under the `elife_bot` area. Maybe that is good separation from other projects, or maybe there is some base environment value it should use instead?

elife medium_footer_pattern for the digest.cfg file and journal.url

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Crossref peer review deposit logic I am working on today, I created this new configuration file value for generating the URL a DOI will forward to.
The pattern for peer reviews is currently the same as the one for components, which make sense for eLife because they are components (currently). Establishing a separate DOI pattern in the configuration makes it easier for me to build, we could potentially change the URL path to view peer reviews, or other users of the library could have their peer reviews in a different place than the article or article components.
This PR should be backwards compatible and can be merged any time.
I don't think it will cause a merge conflict with draft PR https://github.com/elifesciences/elife-bot-formula/pull/44, but if this one is merged first we can check …

peer_review_doi_pattern for Crossref config.

---

Jenkinsfile
salt/elife-bot/init.sls
salt/pillar/elife-bot.sls

For https://github.com/elifesciences/issues/issues/5178
May depend on https://github.com/elifesciences/builder-configuration/pull/93 but maybe it will get the `ci` value from Vault.

Provision GCP credentials from pillar

---

salt/elife-bot/templates/lib-systemd-system-botprocess@.service

* adds GOOGLE_APPLICATION_CREDENTIALS envvar to service workers
cc @gnott

Fix: adds GCP envvar to service worker template

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Re issue https://github.com/elifesciences/elife-crossref-feed/issues/141
When this `crossref.cfg` config file change it merged and deployed, then we will no longer include decision letter or author response component DOIs in Crossref deposits.
As of today, I'm waiting for clarification from Melissa for when this should be deployed.

Add component_exclude_types to crossref.cfg

---

salt/elife-bot/config/opt-elife-bot-letterparser.cfg
salt/elife-bot/init.sls

Related to issue https://github.com/elifesciences/decision-letter-parser/issues/43
I created a config file named `letterparser.cfg` that will be used by the decision letter parser library in an `elife-bot` workflow in the future. I'm adding the file to this formula now before I forget.

Config file letterparser.cfg

---

salt/elife-bot/config/opt-elife-bot-letterparser.cfg

Remaining step to issue https://github.com/elifesciences/issues/issues/5233 which is in my hands to complete.
This, in theory, is how the config can work: there is a default pandoc 2.7 docker image (as specified in the Python library) in the `DEFAULT` section, but in the `elife` section of the config file, we use the docker image tag from the `elifesciences` Docker hub account.
This config file is yet to be loaded and used in the `elife-bot` project, but I intend to be working on that in the next few days. I may merge this myself if I am blocked, otherwise it is open to comments.

Update docker image used for pandoc.

---

salt/elife-bot/config/opt-elife-bot-settings.py

Matches with `elife-bot` PR https://github.com/elifesciences/elife-bot/pull/987 where `letterparser_config_file` and `letterparser_config_section` is added to the example settings file.
I noticed there were a bunch of other settings omitted from the example file in this project, and I added those to this first commit.
There are even more settings missing here, including the digest parser and digest API settings and possibly more (I didn't compare in great detail).
Do any reviewers think it is a good idea to compare all the values in `settings.py` to the https://github.com/elifesciences/elife-bot/blob/develop/settings-example.py file so these are more a one-to-one match?

Some cfg file values for settings.py

---

salt/elife-bot/processes.sls

removes obsolete 14.04/python2 code

Salt 2018.3 / Python 3 upgrade

---

salt/elife-bot/init.sls

* removes some old dependencies on python2 and 14.04
* builds with no problems with the newer Salt `2018.3.4` in Vagrant

python2 removal / salt upgrade

---

salt/elife-bot/config/opt-elife-bot-letterparser.cfg

Re: issue https://github.com/elifesciences/issues/issues/5429
Blocked by Docker hub tag of `elifesciences/pandoc:2.9.1.1` existing first.
To be merged and deployed along with a matching `elife-bot` PR, which I will be preparing now.

docker_image pandoc version 2.9.1.1

---

salt/elife-bot/init.sls
salt/elife-bot/strip-coverletter.sls

fyi @gnott , the 'user' parameter of the `cmd.*` states were deprecated a while back and removed in 2018.3, the version of Salt we're upgrading to. Using `user` doesn't issue a warning so be careful going forwards

replaced 'user' in cmd.* invocations to 'runas'

---

salt/elife-bot/config/opt-elife-bot-settings.py

Re issue https://github.com/elifesciences/issues/issues/5648
Reflecting the recent changes to send PubMed deposits by SFTP, and no longer by FTP, here is the change to credentials in the `settings.py` file.

Swap PubMed FTP credentials for SFTP ones.

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Settings to support issue https://github.com/elifesciences/elife-crossref-feed/issues/145
There will be some new code introduced to the `elife-crossref-xml-generation` library soon which adds Crossmark data to Crossref deposits. The old settings in the `crossref.cfg` file were never used.
I tested how this updated file is still compatible with the currently deployed version of the `elifecrossref` library and all the unit tests pass, as was expected, which should make this PR safe to merge prior to the code being deployed.

Crossmark settings changed in crossref.cfg

---

salt/elife-bot/config/opt-elife-bot-pubmed.cfg

Re issue https://github.com/elifesciences/elife-pubmed-feed/issues/78
In the near future, we want to add the citations of type data, if they have an appropriate `<source>` tag value, to the PubMed dataset objects. In order to do this, we need to populate the `references` of an article when parsing the XML. 
This PR adds `'references'` to the list of article data it parses when populating Article objects.

In pubmed.cfg also populate the references data.

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

As part of developing issue https://github.com/elifesciences/elife-crossref-feed/issues/146, and after some thinking today, it is probably best to put the URL for the Crossref hosted clinical trials registries data into the `crossref.cfg` file, as I've done here. In this way, it is closely aligned with the library that will use the data.
It will eventually be invoked by the `elife-bot`, passing in this config value, and `elife-crossref-xml-generation` library will use it when appropriate.
I have a branch of code that will be ready to PR (hopefully) in a few days (https://github.com/elifesciences/elife-crossref-xml-generation/tree/clinical-trials) and I think this `crossref.cfg` value will remain here unless something really unexpected turns up.

Add clinical_trials_registries to crossref.cfg

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Re issue https://github.com/elifesciences/issues/issues/5743
As part of structured abstracts support in the Crossref generation library, eLife will try sending full JATS abstracts instead of the simplified abstract type the library produces.

eLife Crossref deposits, use jats_abstract true.

---

salt/elife-bot/config/opt-elife-bot-pubmed.cfg

Should be safe to merge ~now that~ after PR https://github.com/elifesciences/elife-bot/pull/1160 is merged, if we don't have to roll back anything due to errors.  Edit: I haven't merged the `elife-bot` PR yet, but I hope to do so today, if tests run successfully.

Remove group_author_contrib_types from pubmed.cfg

---

salt/elife-bot/init.sls

Fix to PR https://github.com/elifesciences/elife-bot-formula/pull/70
On running the formula in a pipline, the branch or revision of the `elife-email-templates` repository may be incorrect, e.g.
```
07:51:14  [54.236.21.243] out: [ERROR   ] Fetch did not successfully retrieve rev 'cb5deab61572c4305973bbde99a74987c606c32d' from git@github.com:elifesciences/elife-email-templates.git: Command 'git rev-parse cb5deab61572c4305973bbde99a74987c606c32d^{commit}' failed: fatal: ambiguous argument 'cb5deab61572c4305973bbde99a74987c606c32d^{commit}': unknown revision or path not in the working tree.
07:51:14  [54.236.21.243] out: Use '--' to separate paths from revisions, like this:
07:51:14  [54.236.21.243] out: 'git <command> [<revision>...] -- [<file>...]'
```
For now, we can probably just use …

Use master branch for elife-email-templates.

---

salt/elife-bot/config/etc-ImageMagick-6-policy.xml
salt/elife-bot/init.sls

Modelled after PR https://github.com/elifesciences/elife-libraries-formula/pull/20
In response to failing pipeline tests on PR https://github.com/elifesciences/elife-bot/pull/1220
There is one failed test in the `elife-bot` PR which introduces the `elifecleaner` library and where it tests getting the page count of a PDF file using `wand`, and the error indicates it is due to the ImageMagick policy file settings. I think add it as a managed file and with it specifying PDF as `read|write` might solve it here too.

Add ImageMagick policy.xml file as managed file.

---

salt/elife-bot/init.sls

It makes sense the next exception `wand.exceptions.WandRuntimeError: ...` did not appear until the `policy.xml` file was configured. After reading the PDF file, I think `ghostscript` is also required here too, as it was in the `elife-libraries-formula`.

Install ghostscript too.

---

salt/pillar/elife-bot.sls

Re `elife-bot` PR https://github.com/elifesciences/elife-bot/pull/1253  adds `era_queue_worker.py`, and this is a part of enabling it as a servicie on the instance.

Add era_queue_worker to the multiservice list.

---

salt/elife-bot/config/opt-elife-bot-settings.py

Re issue https://github.com/elifesciences/issues/issues/6436
Add the `accepted_submission_queue` property to the settings.py file, which will be used soon, if it is a non-blank value.

Add accepted_submission_queue to settings.

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Re issue https://github.com/elifesciences/issues/issues/6569
It should be safe to start generating Crossref deposits to use their version `4.4.2` schema, which is looking to be compatible with the previously used `4.4.1` for eLife's purposes.

Set Crossref schema to 4.4.2 in crossref.cfg

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

To be accompanied with an `elife-bot` PR which will use `elifecrossref==0.10.0`, it will only generate Crossref deposits that are compatible with Crossref schema version `5.3.1`.

In Crossref deposits use schema version 5.3.1

---

salt/elife-bot/config/opt-elife-bot-settings.py

Re issue https://github.com/elifesciences/issues/issues/7026
Soon to be added a new `elife-bot` activity which will upload accepted submission zip files to an output bucket specified by this new settings value.

Add accepted_submission_output_bucket to settings.

---

salt/elife-bot/config/opt-elife-bot-settings.py

After adding some Glencoe FTP settings, I have compared the sample file in this formula repo and added the others that were missing, plus `website_ingest_queue` is no longer used.

Add and remove elife-bot settings.py file values.

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
salt/elife-bot/init.sls

Re issue https://github.com/elifesciences/issues/issues/7652
Hopefully this is configured correctly to add a new `.yaml` file to the project, unless the salt value `elife-bot-downstreamRecipients-cfg` should not be camel case, dunno!

First version of downstreamRecipients.yaml file

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Revisions to earlier PR https://github.com/elifesciences/elife-bot-formula/pull/93 
The outbox details for `publication_email` was missed, and change the workflow name keys for the Crossref deposit ones.

Downstream yaml

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7652
In preparation for `elife-bot` code which relies on the YAML file to populate more FTP and SFTP setting values.

More S/FTP settings to downstreamRecipients.yaml

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7652
More details added to the `downstreamRecipients.yaml` file for in which situations to schedule sending an article be sent to downstream recipients. To accompany an `elife-bot` project PR, and this can be merged early.

More enhancements to downstreamRecipients.yaml

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7652
Last of the rules to define most of the current downstream recipient sending configuration.

More downstreamRecipients.yaml rules.

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7854
Some downstream recipients will have the `<article-id>` tag containing the version DOI of an article removed as part of the workflow logic.

remove_version_doi to downstreamRecipients.yaml

---

salt/elife-bot/init.sls
salt/elife-bot/strip-coverletter.sls

will need to be coordinated with these changes https://github.com/elifesciences/builder-base-formula/pull/381 as the new state depends on the symlink in `docker-native.docker-folder-linking` being updated to point to /bot-tmp/docker
fyi @gnott

adds temporary state to move docker from /ext/docker to /bot-tmp/docker

---

salt/elife-bot/strip-coverletter.sls

instead it's pulled from dockerhub

strip-coverletter is no longer built on highstate.

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7550
Soon to be added a workflow activity to deposit a "minimal" Crossref deposit, to reset related article data, prior to depositing the full data to Crossref again. It will use a separate S3 bucket folder to hold outbox XML files.

DepositCrossrefMinimal added to yaml file.

---

salt/elife-bot/config/opt-elife-bot-assessment_terms.yaml
salt/elife-bot/config/opt-elife-bot-settings.py
salt/elife-bot/init.sls

Re issue https://github.com/elifesciences/issues/issues/8176
Adding another YAML file to the instance. Only if you have time to take a peek at the salt portion @lsh-0, no worries if not.

Add assessment_terms.yaml file

---

salt/elife-bot/config/opt-elife-bot-jatsgenerator.cfg

Updates to the `jatsgenerator.cfg` file,
`elocation_id_pattern` rule will result in different values generated by the next version of `jatsgenerator` library
`elife_preprint` section will be used to generate preprint XML snippets
These changes are backwards compatible with previous versions of `jatsgenerator`, and this PR can be merged immediately.
Re issue https://github.com/elifesciences/issues/issues/8068 for generating preprint XML.

jatsgenerator.cfg elocation_id, elife_preprint

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Accompanies the latest version of `elifecrossref` library, will allow the `elife-bot` workflows to generate DOI deposits for reviewed preprint XML using the `elife_preprint` section of the config file.
Re issue https://github.com/elifesciences/issues/issues/7717

Add elife_preprint section to crossref.cfg

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

Re issue https://github.com/elifesciences/issues/issues/7717
Some `elife-bot` code coming shortly will use this S3 outbox folder for depositing `posted_content` to Crossref.

DepositCrossrefPostedContent to downstream YAML.

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

The `@id` is not required here for now.

crossref.cfg preprint peer review DOI pattern.

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Crossref peer review deposits for preprints are missing a `review_date`. Adding `posted_date` type should help to get the date from the XML file.

In crossref.cfg add pub_date_types for elife_preprint

---

salt/elife-bot/config/opt-elife-bot-crossref.cfg

Changes to `crossref.cfg` for more precise URLs in preprint Crossref deposits.
Re issue https://github.com/elifesciences/issues/issues/8549

crossref.cfg modify elife_preprint, add elife_preprint_version

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml

For a preprint article, queue for `PublicationEmail` sending, every version of them.
Re issue https://github.com/elifesciences/issues/issues/8587

Add preprint PublicationEmail to downstream YAML rules.

---

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
salt/elife-bot/config/opt-elife-bot-settings.py

Re issue https://github.com/elifesciences/issues/issues/8772
Primarily to add `FindNewDocmaps` configuration to the downstream recipients YAML file.
The example `settings.py` can be updated too to include the `docmap_index_url` value. There were many other values missing as compared to the settings currently in use and added those too.

Docmaps downstream config
