salt/elife-bot/config/etc-init-elife-bot-process.conf, salt/elife-bot/newrelic.sls, salt/elife-bot/processes.sls, salt/example.top
Needs:
- https://ci--alfred.elifesciences.org/job/test-elife-bot/35/console to be in `prod`
- `builder-private` to be immediately updated to add `newrelic.sls` to `elife-bot--*`
=> Running bot processes with New Relic wrapper

salt/elife-bot/config/etc-logrotate.d-elife-bot
@gnott: "have looked back to previous weeks to diagnose pubmed errors, etc., so it would be nice if that info was more persistent than just a few days on the bot instance)"
=> Extending persistence of logs on the bot instance

salt/elife-bot/config/opt-elife-bot-crossref.cfg, salt/elife-bot/init.sls
For review please if I did this correctly according to your suggestion on Slack @giorgiosironi  - thanks!
=> Add the crossref.cfg file for the new Crossref library.

salt/elife-bot/init.sls
Depends on https://github.com/elifesciences/elife-bot/pull/449 and https://github.com/elifesciences/elife-poa-xml-generation/pull/288
=> Pin elife-poa-xml-generation version

salt/elife-bot/init.sls
prepping formula for updated strip-coverletter script
merge order:
* this
* strip-coverletter: https://github.com/elifesciences/strip-coverletter/pull/2
=> Feature: updated coverletter

salt/example.top
See https://github.com/elifesciences/builder-base-formula/commit/464d0de027ec784554106ef6aa8f1e44e5fc7cd1
=> ELPP-3360 Expose FTP contents to tests

salt/elife-bot/config/opt-elife-bot-publication_types.yaml
To support a code change in the ``https://github.com/elifesciences/elife-pubmed-xml-generation`` library.
=> Pubmed to support depositing retraction articles.

salt/elife-bot/init.sls
specifically, the installation of imagemagick
=> creating the venv now depends on elife-bot-deps

salt/elife-bot/strip-coverletter.sls, salt/example.top
depends on: https://github.com/elifesciences/strip-coverletter/pull/7
=> Feat dockerised strip coverletter

salt/elife-bot/config/opt-elife-bot-jatsgenerator.cfg, salt/elife-bot/config/opt-elife-bot-packagepoa.cfg, salt/elife-bot/init.sls
Configuration files for the coming PoA libraries. Should have no impact if merged early.
=> Add config files to use newer PoA generation libraries.

salt/example.top, salt/pillar/elife-bot.sls
Needed for https://github.com/elifesciences/jira-import/issues/4311
Depends on https://github.com/elifesciences/builder-base-formula/pull/160
=> Deploy mailcatcher

salt/elife-bot/config/opt-elife-bot-digest.cfg, salt/elife-bot/init.sls, salt/pillar/elife-bot.sls
Could be correct? I will add the real value to builder-private as well.
=> digest.cfg file as a template and replace the IIIF server path.

salt/elife-bot/config/mockserver-elife-bot.sh, salt/example.top, salt/pillar/elife-bot.sls
See https://github.com/elifesciences/builder-base-formula/pull/193
=> Configure mockserver

salt/elife-bot/config/opt-elife-bot-digest.cfg, salt/pillar/elife-bot.sls
Populate the `digest.cfg` file with Medium credentials from the builder.
=> Medium credentials configuration for digest.cfg

salt/elife-bot/config/opt-elife-bot-crossref.cfg
Update to `crossref.cfg` in relation to issue https://github.com/elifesciences/elife-crossref-feed/issues/138. Cannot be merged until the Crossref library is updated in PR https://github.com/elifesciences/elife-bot/pull/862. Fairly small and low impact changes here, I will plan to merge without code review.
=> Crossref deposits use schema 4.4.1

Jenkinsfile
=> adds next-salt to list of alt configs in Jenkinsfile

salt/elife-bot/init.sls, salt/pillar/elife-bot.sls
the 'rmrf_enter' project is long since dead and archived.
fyi @gnott
=> replaces 'rmrf_enter' with 'temporary_files_cleaner'

salt/elife-bot/config/usr-bin-check-file-for-modification.sh, salt/elife-bot/init.sls
worker.log, adds a script that checks for modifications in the last 60 secs
=> worker.log, adds a script that checks for modifications 

salt/elife-bot/config/opt-elife-bot-settings.py
Re issue https://github.com/elifesciences/issues/issues/6745
Blocked by PR https://github.com/elifesciences/elife-bot/pull/1270 which will be merged very soon.
=> Remove settings for Scopus.

salt/pillar/elife-bot.sls
Code is merged and is in a running test pipeline now, after which this new process should be ready to start running, and FYI to @lsh-0
=> Add accepted_submission_queue_worker to services.

salt/elife-bot/config/opt-elife-bot-settings.py
Change to the example settings files to follow changes merged in PR https://github.com/elifesciences/elife-bot/pull/1334
=> Update git_repo_path in settings.py example.

salt/elife-bot/config/opt-elife-bot-settings.py
Re issue https://github.com/elifesciences/issues/issues/7156 in preparation for `boto3`.
=> Add swf_region to settings.py

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Correction or enhancement to PR https://github.com/elifesciences/elife-bot-formula/pull/99, in getting ready to test the sending I forgot to set Scilit recipient to receive XML files only and to send unzipped files, fixed in this PR.
=> Missed some Scilit sending parameters in the YAML.

salt/elife-bot/config/opt-elife-bot-settings.py
Get the settings file to reflect the current settings in `elife-bot`.
=> Sync example settings file values.

salt/elife-bot/config/opt-elife-bot-settings.py
Re issue https://github.com/elifesciences/issues/issues/8237
Updating the `docmap_url_pattern` value in the settings to match new logic.
=> Update docmap_url_pattern in example settings file

salt/elife-bot/config/opt-elife-bot-crossref.cfg
Re issue https://github.com/elifesciences/issues/issues/8502
=> Add iParadigms values to crossref.cfg

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/8539, putting the name of the S3 bucket folder into the YAML file.
=> Add FindNewPreprints to downstreamRecipients.yaml

salt/elife-bot/config/opt-elife-bot-crossref.cfg
Re issue https://github.com/elifesciences/issues/issues/8639
=> Add editor_report_doi_pattern to crossref.cfg, change peer review URL.

salt/elife-bot/config/opt-elife-bot-publicationEmail.yaml, salt/elife-bot/config/opt-elife-bot-settings.py, salt/elife-bot/init.sls
Adding a new YAML config file.
Re issue https://github.com/elifesciences/issues/issues/8588
=> Add publicationEmail.yaml file.

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/8611
=> Add do_not_schedule rules to downstreamRecipients.yaml

salt/elife-bot/config/opt-elife-bot-publicationEmail.yaml
Re issue https://github.com/elifesciences/issues/issues/8874
=> Add expression-of-concern to DoNotSend article_type values.

salt/elife-bot/config/opt-elife-bot-publication_types.yaml
Deploy for support of `Expression of Concern` PubMed deposits.
Re issue https://github.com/elifesciences/issues/issues/6418
=> Add expression-of-concern to PubMed publication_types.yaml file.

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/9092
=> Assessment keywords rule for WoS downstream.

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/9092
=> Add to downstreamRecipients.yaml inadequate

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/8884
=> Do not schedule silent correction preprints for sending emails.

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/9220
=> Add DownloadDocmapIndex folder to downstream YAML

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/8980
=> Add finish_preprint folder to downstreamRecipients.yaml

salt/elife-bot/config/opt-elife-bot-crossref.cfg
Re issue https://github.com/elifesciences/issues/issues/8906
=> Add original-publication to crossref.cfg pub_date_types

salt/example.top, salt/pillar/elife-bot.sls
=> Implement swap on elifebot elifesciences/issues#9278

salt/elife-bot/config/opt-elife-bot-downstreamRecipients.yaml
Re issue https://github.com/elifesciences/issues/issues/9271
=> Add CLOCKSS_Preprint to downstreamRecipients.yaml
